package com.airchina.searchorder.model;

import java.util.Date;

public class SearchOrder {
	private String REGISTER_NUMBERREGISTER_NUMBER;         

	private Integer INTERNATIONAL_FLAGINTERNATIONAL_FLAG;

	private String PAYMENT_IDPAYMENT_ID;                   

	private String USER_IDUSER_ID;                         

	private Integer REGISTER_TYPEREGISTER_TYPE;             

	private Integer REGISTER_STATUSREGISTER_STATUS;         

	private String MOBILE_TYPEMOBILE_TYPE;                 

	private String MOBILE_IPMOBILE_IP;                     

	private String MOBILE_SYS_VERMOBILE_SYS_VER;           

	private String ACCEPT_WAYACCEPT_WAY;                   

	private String CONNECT_PERSONCONNECT_PERSON;           

	private String CONNECT_PHONECONNECT_PHONE;             

	private Integer EXPRESS_TYPEEXPRESS_TYPE;               

	private String REC_NAMEREC_NAME;                       

	private String REC_ADDRREC_ADDR;                       

	private String REC_PHONEREC_PHONE;                    

	private String COUPON_NOCOUPON_NO;                     

	private Integer IF_VALIDIF_VALID;                       

	private Date ACCEPT_DATEACCEPT_DATE;                 

	private Date CANCEL_DATECANCEL_DATE;                 

	private Integer PRINT_TICKET_NOPRINT_TICKET_NO;         

	private Integer CANCEL_TICKET_NOCANCEL_TICKET_NO;       

	private String DEPARTURE_AIRPORTDEPARTURE_AIRPORT;     

	private String ARRIVAL_AIRPORTARRIVAL_AIRPORT;         

	private Integer PRINT_TICKET_FLAGPRINT_TICKET_FLAG;     

	private String AMR_ORDER_NOAMR_ORDER_NO;               

	private String AMR_PAYMENT_IDAMR_PAYMENT_ID;           

	private Integer IF_REFUNDEDIF_REFUNDED;                 
	 
	private String PC_NOPC_NO;
	                             
	private String OLD_OFFICE_CODEOLD_OFFICE_CODE;     
	
	private String OLD_IATA_NOOLD_IATA_NO;                 

	private Integer UP_SHELLUP_SHELL;                       

	private Integer UP_SHELL_FEEUP_SHELL_FEE;               

	private String MOBILE_IP_REALMOBILE_IP_REAL;

	public String getREGISTER_NUMBERREGISTER_NUMBER() {
		return REGISTER_NUMBERREGISTER_NUMBER;
	}

	public void setREGISTER_NUMBERREGISTER_NUMBER(
			String rEGISTER_NUMBERREGISTER_NUMBER) {
		REGISTER_NUMBERREGISTER_NUMBER = rEGISTER_NUMBERREGISTER_NUMBER;
	}

	public Integer getINTERNATIONAL_FLAGINTERNATIONAL_FLAG() {
		return INTERNATIONAL_FLAGINTERNATIONAL_FLAG;
	}

	public void setINTERNATIONAL_FLAGINTERNATIONAL_FLAG(
			Integer iNTERNATIONAL_FLAGINTERNATIONAL_FLAG) {
		INTERNATIONAL_FLAGINTERNATIONAL_FLAG = iNTERNATIONAL_FLAGINTERNATIONAL_FLAG;
	}

	public String getPAYMENT_IDPAYMENT_ID() {
		return PAYMENT_IDPAYMENT_ID;
	}

	public void setPAYMENT_IDPAYMENT_ID(String pAYMENT_IDPAYMENT_ID) {
		PAYMENT_IDPAYMENT_ID = pAYMENT_IDPAYMENT_ID;
	}

	public String getUSER_IDUSER_ID() {
		return USER_IDUSER_ID;
	}

	public void setUSER_IDUSER_ID(String uSER_IDUSER_ID) {
		USER_IDUSER_ID = uSER_IDUSER_ID;
	}

	public Integer getREGISTER_TYPEREGISTER_TYPE() {
		return REGISTER_TYPEREGISTER_TYPE;
	}

	public void setREGISTER_TYPEREGISTER_TYPE(Integer rEGISTER_TYPEREGISTER_TYPE) {
		REGISTER_TYPEREGISTER_TYPE = rEGISTER_TYPEREGISTER_TYPE;
	}

	public Integer getREGISTER_STATUSREGISTER_STATUS() {
		return REGISTER_STATUSREGISTER_STATUS;
	}

	public void setREGISTER_STATUSREGISTER_STATUS(
			Integer rEGISTER_STATUSREGISTER_STATUS) {
		REGISTER_STATUSREGISTER_STATUS = rEGISTER_STATUSREGISTER_STATUS;
	}

	public String getMOBILE_TYPEMOBILE_TYPE() {
		return MOBILE_TYPEMOBILE_TYPE;
	}

	public void setMOBILE_TYPEMOBILE_TYPE(String mOBILE_TYPEMOBILE_TYPE) {
		MOBILE_TYPEMOBILE_TYPE = mOBILE_TYPEMOBILE_TYPE;
	}

	public String getMOBILE_IPMOBILE_IP() {
		return MOBILE_IPMOBILE_IP;
	}

	public void setMOBILE_IPMOBILE_IP(String mOBILE_IPMOBILE_IP) {
		MOBILE_IPMOBILE_IP = mOBILE_IPMOBILE_IP;
	}

	public String getMOBILE_SYS_VERMOBILE_SYS_VER() {
		return MOBILE_SYS_VERMOBILE_SYS_VER;
	}

	public void setMOBILE_SYS_VERMOBILE_SYS_VER(String mOBILE_SYS_VERMOBILE_SYS_VER) {
		MOBILE_SYS_VERMOBILE_SYS_VER = mOBILE_SYS_VERMOBILE_SYS_VER;
	}

	public String getACCEPT_WAYACCEPT_WAY() {
		return ACCEPT_WAYACCEPT_WAY;
	}

	public void setACCEPT_WAYACCEPT_WAY(String aCCEPT_WAYACCEPT_WAY) {
		ACCEPT_WAYACCEPT_WAY = aCCEPT_WAYACCEPT_WAY;
	}

	public String getCONNECT_PERSONCONNECT_PERSON() {
		return CONNECT_PERSONCONNECT_PERSON;
	}

	public void setCONNECT_PERSONCONNECT_PERSON(String cONNECT_PERSONCONNECT_PERSON) {
		CONNECT_PERSONCONNECT_PERSON = cONNECT_PERSONCONNECT_PERSON;
	}

	public String getCONNECT_PHONECONNECT_PHONE() {
		return CONNECT_PHONECONNECT_PHONE;
	}

	public void setCONNECT_PHONECONNECT_PHONE(String cONNECT_PHONECONNECT_PHONE) {
		CONNECT_PHONECONNECT_PHONE = cONNECT_PHONECONNECT_PHONE;
	}

	public Integer getEXPRESS_TYPEEXPRESS_TYPE() {
		return EXPRESS_TYPEEXPRESS_TYPE;
	}

	public void setEXPRESS_TYPEEXPRESS_TYPE(Integer eXPRESS_TYPEEXPRESS_TYPE) {
		EXPRESS_TYPEEXPRESS_TYPE = eXPRESS_TYPEEXPRESS_TYPE;
	}

	public String getREC_NAMEREC_NAME() {
		return REC_NAMEREC_NAME;
	}

	public void setREC_NAMEREC_NAME(String rEC_NAMEREC_NAME) {
		REC_NAMEREC_NAME = rEC_NAMEREC_NAME;
	}

	public String getREC_ADDRREC_ADDR() {
		return REC_ADDRREC_ADDR;
	}

	public void setREC_ADDRREC_ADDR(String rEC_ADDRREC_ADDR) {
		REC_ADDRREC_ADDR = rEC_ADDRREC_ADDR;
	}

	public String getREC_PHONEREC_PHONE() {
		return REC_PHONEREC_PHONE;
	}

	public void setREC_PHONEREC_PHONE(String rEC_PHONEREC_PHONE) {
		REC_PHONEREC_PHONE = rEC_PHONEREC_PHONE;
	}

	public String getCOUPON_NOCOUPON_NO() {
		return COUPON_NOCOUPON_NO;
	}

	public void setCOUPON_NOCOUPON_NO(String cOUPON_NOCOUPON_NO) {
		COUPON_NOCOUPON_NO = cOUPON_NOCOUPON_NO;
	}

	public Integer getIF_VALIDIF_VALID() {
		return IF_VALIDIF_VALID;
	}

	public void setIF_VALIDIF_VALID(Integer iF_VALIDIF_VALID) {
		IF_VALIDIF_VALID = iF_VALIDIF_VALID;
	}

	public Date getACCEPT_DATEACCEPT_DATE() {
		return ACCEPT_DATEACCEPT_DATE;
	}

	public void setACCEPT_DATEACCEPT_DATE(Date aCCEPT_DATEACCEPT_DATE) {
		ACCEPT_DATEACCEPT_DATE = aCCEPT_DATEACCEPT_DATE;
	}

	public Date getCANCEL_DATECANCEL_DATE() {
		return CANCEL_DATECANCEL_DATE;
	}

	public void setCANCEL_DATECANCEL_DATE(Date cANCEL_DATECANCEL_DATE) {
		CANCEL_DATECANCEL_DATE = cANCEL_DATECANCEL_DATE;
	}

	public Integer getPRINT_TICKET_NOPRINT_TICKET_NO() {
		return PRINT_TICKET_NOPRINT_TICKET_NO;
	}

	public void setPRINT_TICKET_NOPRINT_TICKET_NO(
			Integer pRINT_TICKET_NOPRINT_TICKET_NO) {
		PRINT_TICKET_NOPRINT_TICKET_NO = pRINT_TICKET_NOPRINT_TICKET_NO;
	}

	public Integer getCANCEL_TICKET_NOCANCEL_TICKET_NO() {
		return CANCEL_TICKET_NOCANCEL_TICKET_NO;
	}

	public void setCANCEL_TICKET_NOCANCEL_TICKET_NO(
			Integer cANCEL_TICKET_NOCANCEL_TICKET_NO) {
		CANCEL_TICKET_NOCANCEL_TICKET_NO = cANCEL_TICKET_NOCANCEL_TICKET_NO;
	}

	public String getDEPARTURE_AIRPORTDEPARTURE_AIRPORT() {
		return DEPARTURE_AIRPORTDEPARTURE_AIRPORT;
	}

	public void setDEPARTURE_AIRPORTDEPARTURE_AIRPORT(
			String dEPARTURE_AIRPORTDEPARTURE_AIRPORT) {
		DEPARTURE_AIRPORTDEPARTURE_AIRPORT = dEPARTURE_AIRPORTDEPARTURE_AIRPORT;
	}

	public String getARRIVAL_AIRPORTARRIVAL_AIRPORT() {
		return ARRIVAL_AIRPORTARRIVAL_AIRPORT;
	}

	public void setARRIVAL_AIRPORTARRIVAL_AIRPORT(
			String aRRIVAL_AIRPORTARRIVAL_AIRPORT) {
		ARRIVAL_AIRPORTARRIVAL_AIRPORT = aRRIVAL_AIRPORTARRIVAL_AIRPORT;
	}

	public Integer getPRINT_TICKET_FLAGPRINT_TICKET_FLAG() {
		return PRINT_TICKET_FLAGPRINT_TICKET_FLAG;
	}

	public void setPRINT_TICKET_FLAGPRINT_TICKET_FLAG(
			Integer pRINT_TICKET_FLAGPRINT_TICKET_FLAG) {
		PRINT_TICKET_FLAGPRINT_TICKET_FLAG = pRINT_TICKET_FLAGPRINT_TICKET_FLAG;
	}

	public String getAMR_ORDER_NOAMR_ORDER_NO() {
		return AMR_ORDER_NOAMR_ORDER_NO;
	}

	public void setAMR_ORDER_NOAMR_ORDER_NO(String aMR_ORDER_NOAMR_ORDER_NO) {
		AMR_ORDER_NOAMR_ORDER_NO = aMR_ORDER_NOAMR_ORDER_NO;
	}

	public String getAMR_PAYMENT_IDAMR_PAYMENT_ID() {
		return AMR_PAYMENT_IDAMR_PAYMENT_ID;
	}

	public void setAMR_PAYMENT_IDAMR_PAYMENT_ID(String aMR_PAYMENT_IDAMR_PAYMENT_ID) {
		AMR_PAYMENT_IDAMR_PAYMENT_ID = aMR_PAYMENT_IDAMR_PAYMENT_ID;
	}

	public Integer getIF_REFUNDEDIF_REFUNDED() {
		return IF_REFUNDEDIF_REFUNDED;
	}

	public void setIF_REFUNDEDIF_REFUNDED(Integer iF_REFUNDEDIF_REFUNDED) {
		IF_REFUNDEDIF_REFUNDED = iF_REFUNDEDIF_REFUNDED;
	}

	public String getPC_NOPC_NO() {
		return PC_NOPC_NO;
	}

	public void setPC_NOPC_NO(String pC_NOPC_NO) {
		PC_NOPC_NO = pC_NOPC_NO;
	}

	public String getOLD_OFFICE_CODEOLD_OFFICE_CODE() {
		return OLD_OFFICE_CODEOLD_OFFICE_CODE;
	}

	public void setOLD_OFFICE_CODEOLD_OFFICE_CODE(
			String oLD_OFFICE_CODEOLD_OFFICE_CODE) {
		OLD_OFFICE_CODEOLD_OFFICE_CODE = oLD_OFFICE_CODEOLD_OFFICE_CODE;
	}

	public String getOLD_IATA_NOOLD_IATA_NO() {
		return OLD_IATA_NOOLD_IATA_NO;
	}

	public void setOLD_IATA_NOOLD_IATA_NO(String oLD_IATA_NOOLD_IATA_NO) {
		OLD_IATA_NOOLD_IATA_NO = oLD_IATA_NOOLD_IATA_NO;
	}

	public Integer getUP_SHELLUP_SHELL() {
		return UP_SHELLUP_SHELL;
	}

	public void setUP_SHELLUP_SHELL(Integer uP_SHELLUP_SHELL) {
		UP_SHELLUP_SHELL = uP_SHELLUP_SHELL;
	}

	public Integer getUP_SHELL_FEEUP_SHELL_FEE() {
		return UP_SHELL_FEEUP_SHELL_FEE;
	}

	public void setUP_SHELL_FEEUP_SHELL_FEE(Integer uP_SHELL_FEEUP_SHELL_FEE) {
		UP_SHELL_FEEUP_SHELL_FEE = uP_SHELL_FEEUP_SHELL_FEE;
	}

	public String getMOBILE_IP_REALMOBILE_IP_REAL() {
		return MOBILE_IP_REALMOBILE_IP_REAL;
	}

	public void setMOBILE_IP_REALMOBILE_IP_REAL(String mOBILE_IP_REALMOBILE_IP_REAL) {
		MOBILE_IP_REALMOBILE_IP_REAL = mOBILE_IP_REALMOBILE_IP_REAL;
	}


}
